"""empty message

Revision ID: a1a886d623f2
Revises: 6a2ab1fea099
Create Date: 2025-09-08 11:35:07.069920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a886d623f2'
down_revision = '6a2ab1fea099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.alter_column('crew',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('hyperdrive_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.alter_column('hyperdrive_rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('crew',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
